# Generated by Django 6.0.5 on 2026-05-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagador', models.CharField(max_length=255)),
                ('cpf_cnpj_pagador', models.CharField(blank=True, max_length=20, null=True)),
                ('referente', models.TextField()),
                ('emissor', models.CharField(max_length=255)),
                ('cpf_cnpj_emissor', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('cidade', models.CharField(max_length=100)),
                ('data_pagamento', models.DateField()),
                ('forma_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('cheque', 'Cheque'), ('transferencia', 'Transferência/Depósito'), ('cartao', 'Cartão de Crédito/Débito'), ('boleto', 'Boleto')], default='dinheiro', max_length=30)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
